version: "3.8"
services:
  backend:
    # set volume to have changes made locally available in uvicorn localhost:8000/docs (run in container)
    volumes:
      - ./src/backend:/opt/backend/backend
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:80"
    # overrides CMD in Dockerfile to have uvicorn reload functionality for developing at localhost:8000/docs available
    command: >
      sh -c "uvicorn backend.app.main:app --reload --host 0.0.0.0 --port 80"

volumes:
  db-postgres-data:
