version: "3.8"
services:
  db:
    image: postgres:12
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - db-postgres-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  backend:
    # set volume to have changes made locally available in uvicorn localhost:8000/docs (run in container)
    volumes:
      - ./src/backend/app:/opt/backend/backend/app
      - ./src/backend/logs:/opt/backend/backend/logs
      - ./data/models:/opt/backend/backend/data/models
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - POSTGRES_SERVER=${POSTGRES_SERVER}
    depends_on:
      - db
    ports:
      - "8000:80"
    # overrides CMD in Dockerfile to have uvicorn reload functionality for developing at localhost:8000/docs available
    command: >
      sh -c "alembic upgrade head && uvicorn backend.app.main:app --reload --host 0.0.0.0 --port 80"

volumes:
  db-postgres-data:
